### ISSUE TITLE
Cannot get body of large messages

### ISSUE THREAD

**Issue by cjoergensen** [Particular/ServiceControl#473] opened 2015-06-03 08:59 UTC
When trying to get the body for at rather large message ServiceControl throws a "404 - NotFound" exception.

The ContentLength of the message is 516679

**Comment by johnsimons** [comment] 2015-06-08 23:50
@cjoergensen 
That should work, the message size should not cause a 404, are you using the right messageid ?

**Comment by cjoergensen** [comment] 2015-06-09 00:10
@johnsimons messageid should be okay.

**Comment by johnsimons** [comment] 2015-06-09 00:12
very strange indeed, can you send us your SC db ?

**Comment by cjoergensen** [comment] 2015-06-09 00:26
Sure, I will send you an email with the details.

**Comment by johnsimons** [comment] 2015-06-09 22:51
@cjoergensen what version of SC and SI are you on ?

**Comment by johnsimons** [comment] 2015-06-10 01:15
@cjoergensen I figured it out :)
So, I am sad to say that unfortunately we do not store bodies for audit messages that are larger then 100K, see https://github.com/Particular/ServiceControl/blob/6b79b0bd0e51adba69005fc683ca5d35457bc8ff/src/ServiceControl/Operations/BodyStorage/BodyStorageEnricher.cs#L46

So this one seems to be working as designed, that said I do think it is pretty weird and we need to figure out a nicer way to handle this. So I'll be raising an internal issue about it and see what others think.

For now I'll close this one as per design

**Closed by johnsimons** 2015-06-10 01:15 UTC

**Comment by cjoergensen** [comment] 2015-06-10 07:24
@johnsimons Thanks for the update. We sincerely hope that you reconsider the design.

**Comment by johnsimons** [comment] 2015-06-10 07:24
Me too @cjoergensen

**Comment by jinskeep** [comment] 2015-06-10 13:29
We just ran into this exact same issue and found that one of our endpoints pretty consistently has messages in the size range of 150-300K. I would put my vote behind a reconsideration of the design as this endpoint is going to be difficult to troubleshoot if we cannot see the message that is kicking off the handler....
