### ISSUE TITLE
Audit.log created even if unticked in UI

### ISSUE THREAD

**Issue by andreasohlund** [Particular/ServiceControl#861] opened 2016-11-23 10:20 UTC
Installed the latest version for AzureStorageQueues, unticked the audit forwarding. The audit-log queue was still created.

**Comment by johnsimons** [comment] 2016-11-23 21:57
Duplicate of https://github.com/Particular/ServiceControl/issues/849

**Closed by johnsimons** 2016-11-23 21:57 UTC

**Comment by andreasohlund** [comment] 2016-11-24 06:47
Damn, I actually searched before opening this but didn't see it. Sorry for the hazzle
