### ISSUE TITLE
Cannot create an audit instance and select the RavenDB 3.5 engine

### ISSUE THREAD

**Issue by ramonsmits** [Particular/ServiceControl#3533] opened 2023-05-23 12:21 UTC
#### Description

When adding an audit instance you cannot select the RavenDB 3.5 engine. A new audit instance will use RavenDB 3.5

This is needed so that:

1. Users can use the 3.5 engine if the 5 engine is causing issues.
2. Users can restore SC on another instance by installing SC and restore an backup of the database.

#### Expected behavior

The visual installer showing an engine option where the selected default is version 5 but allows selecting version 3.5 or the powershell command to have a engine version argument.

#### Actual behavior

unable to select 3.5

#### Versions

4.26.0 till current (4.30.0)

### Steps to reproduce

1. Install new audit instance

Observe the installer not providing an option to select engine 3.5

#### Workarounds

A workaround is to ensure the audit instance is not using the RavenDB 5 but the previous RavenDB 3.5 engine. Unfortunately, there is no simple method to do this.  Notice that these instances will have RavenDB 3.5 as their storage engine. These cannot be updated to 5 but eventually require a side-by-side installation of a new audit instance that will use RavenDB 5 and the existing audit instance to be uninstalled after the retention period has passed or if the audit data isn't important to be uninstalled immediately once we know why the RavenDB 5 engine is causing problems.

1. Remove the audit instance(s)
2. Uninstall ServiceControl in the server installed applications
3. Download version 2.25.2 (only has RavenDB 3.5) from https://github.com/Particular/ServiceControl/releases/download/4.25.2/Particular.ServiceControl-4.25.2.exe
4. Install 2.25.2
5. Only add the audit instance via ServiceControl Management Utility or Powershell (https://docs.particular.net/servicecontrol/audit-instances/installation-powershell)
6. Install the latest version of ServiceControl (4.30.0 at this writing)
7. Upgrade the audit instances to this version

#### Possible solutions

The visual installer showing an engine option where the selected default is version 5 but allows selecting version 3.5 or the powershell command to have a engine version argument.

**Comment by boblangley** [comment] 2024-11-04 22:25
This is not a bug but a feature request. I am closing this as ServiceControl is now on Raven DB 6.0, the ability to select a Raven DB 3.5 compatible database is no longer possible.

**Closed by boblangley** 2024-11-04 22:25 UTC
Labels: Feature
