### ISSUE TITLE
Unable to remove inactive heartbeats

### ISSUE THREAD

**Issue by pardahlman** [Particular/ServiceControl#2026] opened 2020-05-28 10:44 UTC
I'm running a new install with the following version of monitoring suite:

ServicePulse v1.25.2
ServicePulse v1.25.2
ServiceControl v4.10.0
ServiceControl Monitoring v4.10.0 

It seems to me that the functionality to remove inactive heartbeats from ServicePulse does not work. It disappears from the UI, but reappears automatically after a few seconds.
 
![heartbeats](https://user-images.githubusercontent.com/1032755/83130722-0a595800-a0df-11ea-931d-c4855d43f3c6.gif)

I've seen this behavior in previous versions as well (at least in v1.24.3), but has worked around it by toggling out the endpoints from Configuration > Endpoint heartbeats. However in the latest version of ServicePulse, this menu is no longer present.

Looking at the network traffic, I can see a `DELETE` request to `/api/endpoints/b817450e-5169-12d1-ecc4-ee24a5d7bd7f` that gets a `204 No Content` back, but the `GET` request to `/api/endpoints` contains the endpoint just deleted.

**Comment by dvdstelt** [comment] 2020-06-05 10:00
Thanks for reporting this. We have issues reproducing this. On some occasions, we can reproduce it and on others, we can't, but it's unclear at the moment what the issue is.
We will investigate this further though, but I'm not sure when this will be further investigated or when it will be fixed. We'll report back on this issue though.

**Comment by akselsson** [comment] 2020-06-08 08:59
@dvdstelt This is a blocker for us to upgrade ServicePulse since the function to toggle off endpoints has been removed from `#/configuration/endpoints` in later versions. We are replacing servers on a weekly basis and thus need a way to either remove endpoints or pause alerts in order to use heartbeats to monitor endpoint health.

**Comment by pardahlman** [comment] 2020-06-26 12:17
Would it be possible to temporary reintroduce the ability to toggle endpoints in and out in the heartbeat configuration section? If that functionality can be reliably enabled again, we would not be stuck on an older version of ServiceControl.

**Comment by dvdstelt** [comment] 2020-06-30 11:58
@pardahlman Reintroducing that won't speed up a new release. We have this issue prioritized and it's due to get worked on.

**Comment by pardahlman** [comment] 2020-06-30 13:15
Thanks for the update 👍 Perhaps I misinterpreted you

> We will investigate this further though, but I'm not sure when this will be further investigated or when it will be fixed.

This to me sounded like it was a complex issue and that it may take long time to investigate. If a fix is due in the next release: great! If it will take more time to solve the underlying issue, a work-around would be to just re-introduce the functionality that actually worked 😉 

Keep up the good work!

**Closed** 2020-07-22 07:20 UTC

**Comment by mikeminutillo** [comment] 2020-07-31 06:24
@pardahlman the fix for this has been released in [4.11](https://github.com/Particular/ServiceControl/releases/tag/4.11.0). Please take a look and let us know if it fixes this issue for you.
