### ISSUE TITLE
Receiving RegisterEndpointStartup should be sufficient to add endpoint to known endpoints collection if not already there

### ISSUE THREAD

**Issue by indualagarsamy** [Particular/ServiceControl#564] opened 2015-10-10 19:01 UTC
**Current Problem**
When an endpoint starts with heartbeats, it first sends a RegisterHeartbeat message and then if able to communicate with SC, starts to send heartbeat messages. The RegisterEndpointStartup message results in an event called `EndpointStarted` to be published. And eventually this endpoint gets added in the KnownEndpoints collection.

However, if for some reason, the endpoint registration was lost (perhaps because there was a 2nd instance of SC that processed the first message), restarting the endpoint should re-establish heartbeats and re-register endpoint. However it doesn't.

**Steps to repro**
1. Start ServiceControl
2. Start an Endpoint with the heartbeat plugin installed
3. In RavenStorage, find the endpoint and delete it from `KnownEndpoints`
4. Restart endpoint. Notice that this endpoint will never re-establish itself. 

**Related Desk Case:** https://nservicebus.desk.com/agent/case/13841

**Comment by johnsimons** [comment] 2016-05-10 04:18
@indualagarsamy is this still an issue ?
Also, if there is a 2nd instance of SC running, wouldn't that instance be using a different queue ?

**Comment by indualagarsamy** [comment] 2016-05-12 16:09
@johnsimons - I'll have a look and let you know. I know I raised it a long time ago.

**Comment by indualagarsamy** [comment] 2016-05-12 16:10
@johnsimons - Have you tried the steps I listed in the issue description?

**Comment by johnsimons** [comment] 2016-05-12 22:22
@indualagarsamy I haven't tried the steps because it involves a manual hack "In RavenStorage, find the endpoint and delete it from KnownEndpoints" and I am not sure why a knownendpoint would all of the sudden disappear ?

**Comment by johnsimons** [comment] 2016-06-02 06:15
@indualagarsamy I still think that to get to this situation the database would need to be hacked, I haven't been able to reproduce this on its own.
If you have time to sit with me and show how to reproduce it let me know but for now I will close this.

**Closed by johnsimons** 2016-06-02 06:15 UTC
Labels: Type: Bug
