### ISSUE TITLE
The title should be SC management ?

### ISSUE THREAD

**Issue by johnsimons** [Particular/ServiceControl#515] opened 2015-09-01 03:20 UTC
![image](https://cloud.githubusercontent.com/assets/122651/9595635/26c382aa-50ac-11e5-8615-b7956150760f.png)

**Comment by petersgiles** [comment] 2015-09-01 07:23
Do you mean that you want the Logo at the top from ServiceControl to ServiceControlInstaller?

**Comment by johnsimons** [comment] 2015-09-01 07:43
Yep, that is what we call it in the shortcut menu:
![image](https://cloud.githubusercontent.com/assets/122651/9598670/eb79d06c-50d0-11e5-95ae-41ce66c72e06.png)

So IMO those names should match

**Comment by gbiellem** [comment] 2015-09-01 07:58
@johnsimons the issue is we don't have an agreed on name for this thing.  

I put in the name ServiceControl Management as a place holder but there is no firm agreement on the name. Suggestions welcome :)

**Comment by distantcam** [comment] 2015-09-02 03:52
I'm fine with ServiceControl Management. @gbiellem Who disagreed with the name?

We could always use `ServiceControl Management Platform Express for Enterprise 2015 Q4 with ServiceControl 1.6` (SMPEE2015Q4SC1.6 for short).

**Comment by petersgiles** [comment] 2015-09-02 04:19
+1 Ship it!

**Comment by johnsimons** [comment] 2015-09-02 05:17
:+1: on ServiceControl Management

**Comment by gbiellem** [comment] 2015-09-02 07:25
@distantcam  

It was @sergioc who was :-1:  on the name

**Comment by sergioc** [comment] 2015-09-02 07:38
I'll just copy here the comments I previously placed in Slack:

> @greg: I really advise against calling the tool “ServiceControl Management”. I agree that the tool is about managing, but a direct linguistic representation of the tool’s functionality does not justify the awkwardness when referring to the tool in customer support, documentation and anywhere else where we need to write about it. In addition, “ServiceControl Management" still collides a bit with Windows "Service Control Manager”.

> I strongly advise using a noun in the name that works standalone and doesn’t require an auxiliary noun outside the name in any situation + is completely different from “Service Control Manager”.

Example of awkwardness: 
- "Hello. Do have the latest version of ServiceControl Management?"
- "Hello. Do have the latest version of THE ServiceControl Management?"
- "Please open ServiceControl Management"
- "Locate the ServiceControl Management folder"

I'd be interested in hearing comments on this from @brittking & @udidahan.

**Comment by sergioc** [comment] 2015-09-02 07:40
I suspect you might be OK with the name because I doubt you've been referring to it as "ServiceControl Management" in conversations...

**Comment by distantcam** [comment] 2015-09-02 07:42
@sergioc So what's the alternative then? What should it be called?

**Comment by gbiellem** [comment] 2015-09-02 07:45
@sergioc  ServiceControl Configuration?

**Comment by petersgiles** [comment] 2015-09-02 07:46
ServiceControl Control ?

**Comment by sergioc** [comment] 2015-09-02 07:48
LOL @petersgiles 

I've suggested "ServiceControl Utility" before.

**Comment by gbiellem** [comment] 2015-09-02 10:40
@sergioc 

IMO since this is part of the installation and on going configuration of ServiceControl  it makes sense to have it named after the function it performs.  "ServiceControl Utility" and "ServiceControl Management" both fail to captures that and seem very generic.  

Also remember we aren't just naming the WPF app but also the Powershell module that ships with it.
So we need a name that works with both or two separate names. 

IMO we should go with something with "installation",  "configuration", "admin"  in the name and we can append the obligatory descriptor at the end (e.g. tool, manager, utility, shell or powershell)

So this would give us names like:

ServiceControl Installation Center  &  ServiceControl Installation PS Module 
ServiceControl Admin Tool &  ServiceControl Admin Shell 
ServiceControl Config Manager &  ServiceControl Configuration Shell 
ServiceControl Config Utility &  ServiceControl Configuration PowerShell 

Would you be happier with any of these or some other derivation?

Lets set up a meeting of the TF tomorrow and choose something. If we can't come to an agreement then we can pull in some to break any deadlock.  Agreed?

**Comment by sergioc** [comment] 2015-09-02 11:51
@gbiellem agreed.

>ServiceControl Admin Tool & ServiceControl Admin Shell
ServiceControl Config Manager & ServiceControl Configuration Shell
ServiceControl Config Utility & ServiceControl Configuration PowerShell

Any of the above sound good to me. Something similar probably yes too. However, where you use config/configuration, I'd stick to either config for both or configuration for both.

**Comment by gbiellem** [comment] 2015-09-03 08:05
Taskforce decided on:

- ServiceControl Management Utility
- ServiceControl Management PowerShell

**Comment by gbiellem** [comment] 2015-09-03 08:27
@sergioc please  provide updated graphic for main screen

**Comment by sergioc** [comment] 2015-09-03 09:03
Updated graphic: https://www.dropbox.com/s/4y6dl3azliq0rbk/sc-app-logo.svg?dl=0

Placement reference:

![screenshot 2015-09-03 10 58 08](https://cloud.githubusercontent.com/assets/493451/9654485/60af679c-522b-11e5-9b37-3bf4200be897.png)

**Comment by sergioc** [comment] 2015-09-08 10:13
@distantcam font for title: https://www.dropbox.com/s/xdcmorwluc83d3v/Lato-Bold.ttf?dl=0

**Comment by distantcam** [comment] 2015-09-10 06:16
Looks good, yes?
![image](https://cloud.githubusercontent.com/assets/1298847/9781409/7463463c-57c6-11e5-8d06-7be430f1e980.png)

**Comment by sergioc** [comment] 2015-09-10 06:49
lol @distantcam

**Comment by sergioc** [comment] 2015-09-10 09:29
@distantcam judging from screenshot with the joke above, it doesn't seem that sizing and padding around logo corresponds to the reference shown in https://github.com/Particular/ServiceControl/issues/515#issuecomment-137385123

**Comment by distantcam** [comment] 2015-09-10 11:55
@sergioc Good point! Fixed now. (See how the icon is smaller.)

![image](https://cloud.githubusercontent.com/assets/1298847/9787488/d2cb0e24-57f5-11e5-85e6-7081a6212edf.png)

**Closed by distantcam** 2015-09-10 11:55 UTC
Labels: Tag: Installer
