### ISSUE TITLE
Unable to start ServiceControl in Maintenance mode

### ISSUE THREAD

**Issue by grimland** [Particular/ServiceControl#1575] opened 2019-01-25 05:28 UTC
When starting ServiceControl v3.6.0 in maintenance mode the service fails to restart:

System.ComponentModel.Win32Exception (0x80004005): The service did not respond to the start or control request in a timely fashion

**From Event Viewer:**
Application: ServiceControl.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Net.HttpListenerException
   at System.Net.HttpListener.AddAllPrefixes()
   at System.Net.HttpListener.Start()
   at Microsoft.Owin.Host.HttpListener.OwinHttpListener.Start(System.Net.HttpListener, System.Func`2<System.Collections.Generic.IDictionary`2<System.String,System.Object>,System.Threading.Tasks.Task>, System.Collections.Generic.IList`1<System.Collections.Generic.IDictionary`2<System.String,System.Object>>, System.Collections.Generic.IDictionary`2<System.String,System.Object>, System.Func`2<System.String,System.Func`6<System.Diagnostics.TraceEventType,Int32,System.Object,System.Exception,System.Func`3<System.Object,System.Exception,System.String>,Boolean>>)
   at Microsoft.Owin.Host.HttpListener.OwinServerFactory.Create(System.Func`2<System.Collections.Generic.IDictionary`2<System.String,System.Object>,System.Threading.Tasks.Task>, System.Collections.Generic.IDictionary`2<System.String,System.Object>)

Exception Info: System.Reflection.TargetInvocationException
   at System.RuntimeMethodHandle.InvokeMethod(System.Object, System.Object[], System.Signature, Boolean)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(System.Object, System.Object[], System.Object[])
   at System.Reflection.RuntimeMethodInfo.Invoke(System.Object, System.Reflection.BindingFlags, System.Reflection.Binder, System.Object[], System.Globalization.CultureInfo)
   at Microsoft.Owin.Hosting.ServerFactory.ServerFactoryAdapter.Create(Owin.IAppBuilder)
   at Microsoft.Owin.Hosting.Engine.HostingEngine.Start(Microsoft.Owin.Hosting.Engine.StartContext)
   at Raven.Database.Server.OwinHttpServer.EnableHttpServer(Raven.Database.Config.InMemoryRavenConfiguration)
   at Raven.Server.RavenDbServer.Initialize(System.Action`1<Raven.Database.Server.RavenDBOptions>)
   at Raven.Database.Client.EmbeddedDocumentStore.Initialize()
   at Raven.Client.Embedded.EmbeddableDocumentStore.Initialize()
   at ServiceControl.Infrastructure.RavenDB.RavenBootstrapper.StartRaven(Raven.Client.Embedded.EmbeddableDocumentStore, ServiceBus.Management.Infrastructure.Settings.Settings, ServiceControl.Infrastructure.MarkerFileService, Boolean)
   at Particular.ServiceControl.MaintenanceBootstrapper.Run(Particular.ServiceControl.Hosting.HostArguments)
   at Particular.ServiceControl.Commands.CommandRunner.Execute(Particular.ServiceControl.Hosting.HostArguments)
   at Particular.ServiceControl.Program.Main(System.String[])

**Comment by WilliamBZA** [comment] 2019-01-28 10:17
Can you find the servicecontrol log files and see if there is anything there @grimland? You can find the log files [here](https://docs.particular.net/servicecontrol/logging#logging-location).

**Comment by grimland** [comment] 2019-01-29 05:34
There were no entries in the ravenlog file and the other logfile contained

2019-01-29 15:14:05.2662|1|Info|ServiceBus.Management.Infrastructure.Settings.Settings|No settings found for error log queue to import, default name will be used
2019-01-29 15:14:05.3302|1|Info|ServiceBus.Management.Infrastructure.Settings.Settings|No settings found for audit log queue to import, default name will be used
2019-01-29 15:14:05.5412|1|Info|ServiceControl.Infrastructure.RavenDB.RavenBootstrapper|Loading Embedded RavenDB license

**Comment by boblangley** [comment] 2019-02-05 03:44
This could be a duplicate of https://github.com/Particular/ServiceControl/issues/1536 which was fixed in 3.4.1.

@grimland Can you confirm your ServiceControl instance has been upgraded to 3.6.0? You can check in the ServiceControl Management Utility as seen in the screenshot in this part of our installation guide: https://docs.particular.net/servicecontrol/installation#using-servicecontrol-management-to-upgrade-servicecontrol-instances

**Comment by grimland** [comment] 2019-05-13 00:50
It has been awhile since I replied on this issue, but I tried giving the account admin privileges and it worked. The problem is the service account used to run the service control instance is not allowed admin privileges. Is there a more specific set of privileges that it could be given to work?

**Comment by mikeminutillo** [comment] 2019-05-13 03:17
@grimland does this issue only occur when you try to run the instance in maintenance mode?

If the issue only happens when you start maintenance mode, then I would guess then I wonder if you might be missing a URLACL for the maintenance port. 

Was this instance created as version 3.6.0 or has it been upgraded from a previous version? If upgraded from a previous version, which one? Do you manage the instance using the ServiceControl Management Utility or via the powershell scripts?

**Comment by grimland** [comment] 2019-05-13 04:44
Yes it is only in maintenance mode. 

There is an existing URLACL already for the maintenance port

Reserved URL            : http://localhost:43336/
    User: BUILTIN\Users
        Listen: Yes
        Delegate: No
        SDDL: D:(A;;GX;;;BU)

This Service Control Manager was originally 3.4.1 but was upgraded to 3.6.0. The service control instance was deployed as 3.6.0. The instance is managed through the ServiceControl Management Utility, but once the ServiceControl.exe.config file for the instance is updated to maintenance mode the service will no longer start using the Service Control Management or through services mmc.

<add key="ServiceControl/MaintenanceMode" value="True" />

**Comment by mikeminutillo** [comment] 2019-05-13 06:18
@grimland Can I ask you to please [open a support case](https://particular.net/support). If you can export the event from the Event Viewer, as well as the ServiceControl config file, and include both in the case, that would help. Thanks.

**Comment by mikeminutillo** [comment] 2019-05-13 06:19
Also, can you verify that the service account you are running under is a member of `BUILTIN\Users`?

**Comment by mikeminutillo** [comment] 2019-05-17 02:00
After investigating this, we discovered this bug https://github.com/Particular/ServiceControl/issues/1643

@grimland I am closing this issue since we got you unstuck. If you run into any more problems feel free to re-open this issue or raise a new one.

**Closed by mikeminutillo** 2019-05-17 02:00 UTC
