### ISSUE TITLE
Cannot uninstall Service Control instance

### ISSUE THREAD

**Issue by kye** [Particular/ServiceControl#604] opened 2015-12-02 00:06 UTC
When uninstalling an instance the remove logs and DB checkboxes are uncheckable. The controls are enabled but it looks like they are unchecked automatically. They "flicker".

![flicker](https://cloud.githubusercontent.com/assets/1609968/11518378/c21e1c80-98e4-11e5-8009-08f9d5c67c22.png)

**Comment by gbiellem** [comment] 2015-12-02 00:58
Hi @Kye 

I think this is a duplicate of  [#599](https://github.com/Particular/ServiceControl/issues/599) which was fixed in the [v1.8.0 release](https://github.com/Particular/ServiceControl/releases/tag/1.8.0)

Can you confirm?

**Comment by gbiellem** [comment] 2015-12-14 04:29
Hi @kye,  I haven't heard back form you so I'm going to close this as a duplicate of #599 which was addressed in the 1.8 release.   If you think this is somehow different please reopen.

**Closed by gbiellem** 2015-12-14 04:29 UTC

**Comment by kye** [comment] 2015-12-14 08:34
Sorry. It was an earlier version, I just didn't have a chance to retest.
