### ISSUE TITLE
Retry groups not retrying

### ISSUE THREAD

**Issue by WilliamBZA** [Particular/ServiceControl#636] opened 2016-02-03 14:14 UTC
Related to desk case 16617

ServiceControl receives a RetryAllMessagesInGroup message, but silently ends there.

**Comment by WilliamBZA** [comment] 2016-02-10 10:56
This appears to be related to stale indexes in RavenDB. The following actions were taken:

- ServiceControl was make to point to new queues where no new messages would be receieved
- The RavenDB database was moved to a new drive with 2.5x the random read/write performance of the previous drive
- The CPU was also upgraded to 8 core
- The RAM was upgraded to 32GB
- ServiceControl was left to run so that the database indexes could catch up and become non-stale
- The application pool garbage collection was configured to have gcServer set to true

Retries were successful after this however there still appears to be an issue of SC not picking up new messages from the SQL transport. Still investigating this

/cc @ramonsmits @johnsimons @mikeminutillo @mauroservienti @sfarmar @petersgiles

**Comment by johnsimons** [comment] 2016-02-15 01:28
@WilliamBZA any other issues ? Or can we close this now ?

**Comment by ramonsmits** [comment] 2016-02-15 22:18
It can be closed. The cause is the two stream based tasks operating on lots of documents which is super slow and cause lots of IO blocking all other 'short' handlers.

**Closed by ramonsmits** 2016-02-15 22:18 UTC
Labels: State: In Progress, Type: Bug
