### ISSUE TITLE
License writen to HKLM but read from different location

### ISSUE THREAD

**Issue by ramonsmits** [Particular/ServiceControl#677] opened 2016-02-19 10:13 UTC
The read order currently is:

- File: `License/License.xml`
- File: `ParticularPlatformLicense.xml`
- Registry: HKCU\SOFTWARE\ParticularSoftware\@License
- Registry: HKLM\SOFTWARE\ParticularSoftware\@License

When importing a license it is written to HKLM. That does not make sense. If a license is present on any of the other locations service control will not us the new license.

**Comment by gbiellem** [comment] 2016-02-19 10:24
Duplicate of https://github.com/Particular/ServiceControl/issues/629

We are going to read all locations and choose the most appropriate license rather than have a read order.

**Closed by gbiellem** 2016-02-19 10:24 UTC
Labels: Type: Bug
