### ISSUE TITLE
Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:44445

### ISSUE THREAD

**Issue by ramonsmits** [Particular/ServiceControl#3520] opened 2023-05-16 09:42 UTC
#### Description

THe following log entry is written:

> 2023-05-12 12:36:16.8408|57|Error|NServiceBus.CustomChecks.TimerBasedPeriodicCheck|'ServiceControl.CheckRavenDBIndexLag' implementation failed to run.
System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:44445
   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)

It is unclear why, it seems to be suggesting that the RavenDB 5 instance is down/terminated. It is unclear if that is happening because the SC is gracefully shutting down or if the RavenDB 5 server crashed.

If this is a graceful shutdown of SC audit instance this should not be logged. If it isn't then maybe the RavenDB 5 server sub process needs to be restarted/recovered or when this is detected the SC instance MUST be terminated because it is no longer healthy.

#### Expected behavior

Not have this log entry at all and the state to be handled gracefully. It its expected (during shutdown) don't log it, if it is unexpected recoverability actions to be performed (restart ravendb server instance OR failfast SC instance)

#### Actual behavior

Unknown, confusing log entries

#### Versions

Unknown, likely latest 4.30.0

### Steps to reproduce

1. Start ServiceControl Audit instance running with embedded RavenDB 5, as message store. 
2. Kill `dotnet.exe` process running embedded RavenDB
3. There will be entries in the log file similar to:

```shell
2023-06-20 12:44:14.8489|68|Error|NServiceBus.CustomChecks.TimerBasedPeriodicCheck|'ServiceControl.CheckRavenDBIndexLag' implementation failed to run.
System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:44445
   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
```

### Relevant log output

```shell
2023-05-12 12:36:16.8408|57|Error|NServiceBus.CustomChecks.TimerBasedPeriodicCheck|'ServiceControl.CheckRavenDBIndexLag' implementation failed to run.
System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:44445
   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Raven.Client.Http.RequestExecutor.<SendRequestToServer>d__116`1.MoveNext() in C:\Builds\RavenDB-Stable-5.4\54038\src\Raven.Client\Http\RequestExecutor.cs:line 1039
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Raven.Client.Http.RequestExecutor.<ExecuteAsync>d__114`1.MoveNext() in C:\Builds\RavenDB-Stable-5.4\54038\src\Raven.Client\Http\RequestExecutor.cs:line 866
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Raven.Client.Documents.Operations.MaintenanceOperationExecutor.<SendAsync>d__13`1.MoveNext() in C:\Builds\RavenDB-Stable-5.4\54038\src\Raven.Client\Documents\Operations\MaintenanceOperationExecutor.cs:line 62
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ServiceControl.CheckRavenDBIndexLag.<PerformCheck>d__1.MoveNext() in /_/src/ServiceControl.Audit.Persistence.RavenDb5/CustomChecks/CheckRavenDBIndexLag.cs:line 25
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.CustomChecks.TimerBasedPeriodicCheck.<Run>d__4.MoveNext()
```

**Comment by jpalac** [comment] 2023-06-21 00:31
Changes were implemented in https://github.com/Particular/ServiceControl/pull/3590 to try and restore the RavenDB server connection if it is lost while the Audit instance is running.

The audit instance uses a custom CustomCheckManager which was not handling OperationCancelled exceptions - this was rectified in https://github.com/Particular/ServiceControl/pull/3602.

The main instance uses NServiceBus.CustomChecks v3. In that version, the custom check runner [does not handle OperationCancelled exception](https://github.com/Particular/NServiceBus.CustomChecks/blob/release-3.0/src/NServiceBus.CustomChecks/TimerBasedPeriodicCheck.cs#L31) hence we're seeing occasional errors for some of the main instance custom checks when the instance is being shutdown during their run.
In v4 of NServiceBus.CustomChecks [the problem is fixed](https://github.com/Particular/NServiceBus.CustomChecks/blob/release-4.0/src/NServiceBus.CustomChecks/TimerBasedPeriodicCheck.cs#L68) hence when we upgrade SC to use NSB 8 the main instance will be sorted as well.

Closing this issue as the above changes should resolve it: either restarting the RavenDB server if it's unexpectedly shut down or not displaying the error messages if we are in the middle of shutting down the audit instance.

**Closed by jpalac** 2023-06-21 00:31 UTC
Labels: Bug
