### ISSUE TITLE
ServiceControl Monitoring with RabbitMQ transport can't be started

### ISSUE THREAD

**Issue by mozerov** [Particular/ServiceControl#3662] opened 2023-08-14 11:13 UTC
#### Description
ServiceControl Monitoring instance with RabbitMQ transport can't be started due to an unhandled exception. 

#### Event Viewer log:
```
Application: ServiceControl.Monitoring.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ArgumentException
   at System.Data.Common.DbConnectionOptions.GetKeyValuePair(System.String, Int32, System.Text.StringBuilder, Boolean, System.String ByRef, System.String ByRef)
   at System.Data.Common.DbConnectionOptions.ParseInternal(System.Collections.Hashtable, System.String, Boolean, System.Collections.Hashtable, Boolean)
   at System.Data.Common.DbConnectionOptions..ctor(System.String, System.Collections.Hashtable, Boolean)
   at System.Data.Common.DbConnectionStringBuilder.set_ConnectionString(System.String)
   at ServiceControl.Transports.RabbitMQ.QueueLengthProvider+QueryExecutor.Initialize()
   at ServiceControl.Transports.RabbitMQ.QueueLengthProvider.Start()
   at NServiceBus.Features.FeatureStartupTaskController.Start(NServiceBus.ObjectBuilder.IBuilder, NServiceBus.IMessageSession)
   at NServiceBus.Features.FeatureActivator+<StartFeatures>d__5.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at NServiceBus.StartableEndpoint+<Start>d__1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at NServiceBus.HostingComponent+<Start>d__7.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at NServiceBus.ExternallyManagedContainerHost+<Start>d__9.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at NServiceBus.Extensions.Hosting.NServiceBusHostedService+<StartAsync>d__1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Extensions.Hosting.Internal.Host+<StartAsync>d__12.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions+<RunAsync>d__4.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions+<RunAsync>d__4.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at ServiceControl.Monitoring.CommandRunner+<Run>d__1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at ServiceControl.Monitoring.Program+<Main>d__1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at ServiceControl.Monitoring.Program.<Main>(System.String[])
```

#### Configuration file
```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
    <appSettings>
        <add key="Monitoring/TransportType" value="ServiceControl.Transports.RabbitMQ.RabbitMQQuorumConventionalRoutingTransportCustomization, ServiceControl.Transports.RabbitMQ" />
        <add key="Monitoring/HttpHostName" value="localhost" />
        <add key="Monitoring/HttpPort" value="33633" />
        <add key="Monitoring/LogPath" value="C:\ProgramData\Particular\ServiceControl\Particular.Monitoring\Logs" />
        <add key="Monitoring/ErrorQueue" value="Errors" />
    </appSettings>
    <connectionStrings>
        <add name="NServiceBus/Transport" connectionString="amqps://username:password@instance.name.cloudamqp.com/username" />
    </connectionStrings>
</configuration>
```

#### Versions
v4.32.2

### Steps to reproduce

Add a monitoring instance with the default configuration. For transport choose RabbitMQ - Conventional routing topology (quorum queues) and specify **amqps://** connection string. Click 'Save'. Wait a few seconds and click 'Refresh' in ServiceControl Management.

**Expected result:**
Monitoring service is started and running

**Actual result:**
Monitoring service is stopped

**Comment by jpalac** [comment] 2023-08-15 00:16
@mozerov Thank you for posting your findings. We are aware of this particular issue - you can find it recorded here: https://github.com/Particular/ServiceControl/issues/3401

It provides a [work around](https://github.com/Particular/ServiceControl/issues/3401#issuecomment-1424815532) that should address your current problem.

If you have any more concerns in relation to this please post them on the [original issue](https://github.com/Particular/ServiceControl/issues/3401) - I will be closing this one as a duplicate.

**Comment by jpalac** [comment] 2023-08-15 00:16
Closing as a duplicate of https://github.com/Particular/ServiceControl/issues/3401

**Closed by jpalac** 2023-08-15 00:16 UTC
Labels: Bug
