### ISSUE TITLE
SCMU menu dropdown menus are misaligned

### ISSUE THREAD

**Issue by bording** [Particular/ServiceControl#1374] opened 2018-08-21 15:59 UTC
After upgrading to 3.0.0, I'm seeing the following in SCMU:

![image1](https://user-images.githubusercontent.com/753669/44413492-7d609280-a539-11e8-9545-c021d72bcd57.png)
![image2](https://user-images.githubusercontent.com/753669/44413493-7d609280-a539-11e8-8570-defb7bf07971.png)
![image3](https://user-images.githubusercontent.com/753669/44413494-7d609280-a539-11e8-840d-1ab6c903adc3.png)

@danielmarbach has said he is seeing the same behavior, but @boblangley is not seeing it on his computer.

**Comment by boblangley** [comment] 2018-08-21 19:55
Previous report of this issue: #1117

**Comment by danielmarbach** [comment] 2018-08-22 07:05
I can repro it on my workstation with Geforce GTX 1060. Dualscreen 4k, 60Hz Scaling 100% nor 150%
But I can't repro it on my laptop with Geforce MX150 4k Scaling 100% nor 150%

**Comment by danielmarbach** [comment] 2018-08-29 07:43
@SzymonPobiega @WilliamBZA has been working on this but a solution is not yet merged as I recall.

**Comment by danielmarbach** [comment] 2018-08-29 07:43
This is the branch https://github.com/Particular/ServiceControl/tree/dpi-fixes

**Comment by bording** [comment] 2018-10-11 19:53
I really think this should be prioritized to be fixed sooner rather than later. It's UI that users directly interact with, and makes SCMU look terrible and confusing.

**Comment by HEskandari** [comment] 2018-10-22 07:55
I have encountered this as well. I'm running a Win10 on a VM on my Mac (not sure if that is high DPI?).

👍 	on fixing this as soon as possible. It is very annoying to say the least.

**Comment by bording** [comment] 2018-10-24 22:30
@WilliamBZA Your comment (https://github.com/Particular/ServiceControl/pull/1469#issuecomment-431759095) implies this is related to High DPI, but I'm seeing this with regular 100% scaling as well.

**Comment by WilliamBZA** [comment] 2018-10-25 04:39
It's a theory. I'm not sure DPI and Scaling are always related. Once this issue goes into progress I'm sure whoever the taskforce is will determine the proper cause.

**Comment by aleksandr-samila** [comment] 2019-05-29 19:56
Doing a weekly review and reviewing this doc https://docs.particular.net/samples/servicecontrol/adapter-mixed-transports/ I downloaded SC. During installation I saw such misalignment.

***1.*** 
![image](https://user-images.githubusercontent.com/5980232/58586492-da753b80-8263-11e9-938b-140889e57115.png)

and 
***2.*** 
![image](https://user-images.githubusercontent.com/5980232/58586582-13adab80-8264-11e9-8c31-04f0f618b87e.png)

I wanted to create a new issue but found this one. So I decided to reopen it.

My current system is: Windows 10 64. Laptop with 4k display + 2560x1440 Dell monitor. The problem appears on both displays

**Comment by HEskandari** [comment] 2019-05-30 08:55
I don't know. Mine was working fine on 3.7.0. Just upgraded to 3.7.2 and still works fine (Mac Book Pro display, as well as running it in a UW display).

**Comment by mikeminutillo** [comment] 2019-05-31 01:25
Mine does not. Lenovo Yoga C930. 

Main Display: 3840x2160 (200% scaling)
Secondary Display: 1920x108 (100% scaling) (Located above the primary)

Windows 10 Pro (Version 1803 Build 17134.765)

**Comment by mikeminutillo** [comment] 2019-05-31 02:07
Reset my main display to 100% scaling, unplugged my secondary display and restarted. Symptoms remain.

**Comment by HEskandari** [comment] 2019-05-31 02:08
@mikeminutillo 	is it broken on both screens?

**Comment by mikeminutillo** [comment] 2019-05-31 02:10
Yes. Always too far to the left

**Comment by HEskandari** [comment] 2019-05-31 02:16
I still can't reproduce it here. It is very similar to what's discussed here though: https://stackoverflow.com/questions/46179366/horizontaloffset-goes-in-the-wrong-direction-for-high-dpi-primary-screen

**Comment by mikeminutillo** [comment] 2019-05-31 03:28
I can confirm the sample code attached to that StackOverflow question also fails on my machine. Does it work for you @HEskandari ?

**Comment by HEskandari** [comment] 2019-05-31 14:50
Can you check if tweaking the settings here makes any difference?

<img width="466" alt="Screen Shot 2019-05-31 at 12 21 25 pm" src="https://user-images.githubusercontent.com/132117/58714006-257b8400-8407-11e9-8c5c-1e5bd6f6e7a7.png">

**Comment by aleksandr-samila** [comment] 2019-06-01 00:38
Didn't help

**Comment by HEskandari** [comment] 2019-06-01 01:16
@aleksandr-samila @mikeminutillo Does it still show incorrectly when you have your second monitor disconnected from your laptop?

**Comment by aleksandr-samila** [comment] 2019-06-01 01:36
Yes, just checked. Everything still the same. Didn't help

**Comment by mikeminutillo** [comment] 2019-08-07 06:41
@aleksandr-samila by any chance is your laptop usable as a tablet?

I discovered a setting under Control Panel -> Tablet PC Settings -> Other called Handedness. If it is set to right-handed (the default), then Popup placements are reversed (to prevent popups from appearing under your hand). If I set it to left-handed, then SCMU drop-downs all work as expected. 

![image](https://user-images.githubusercontent.com/124014/62600252-ff9bbf80-b920-11e9-830f-e8467d1287f6.png)

[Popup positioning post on WPF Forums](https://social.msdn.microsoft.com/Forums/vstudio/en-US/19ef3d33-01e5-45c5-a845-d64f9231001c/popup-positioningalignments?forum=wpf)

We can detect handedness with `SystemParameters.MenuDropAlignment` and/or `SystemParameters.IsMenuDropRightAligned`. I am not sure which one is correct and they both always return the same thing for me. It's worth noting that setting appears to be cached for the app once it is read so if you change the setting you need to restart the app to see the new value.

**Comment by mikeminutillo** [comment] 2019-08-07 06:48
Looks like `MenuDropAlignment` is [the right one to use](https://github.com/dotnet/wpf/blob/ac9d1b7a6b0ee7c44fd2875a1174b820b3940619/src/Microsoft.DotNet.Wpf/src/PresentationFramework/System/Windows/Controls/Primitives/Popup.cs#L2474)

**Comment by aleksandr-samila** [comment] 2019-08-07 06:55
Since I reopened this issue I've got a new laptop. Checked once again just now - the problem still exists.

And I never used my laptops as a tablet.

And yes, after changing this settings - everything become Ok.

**Closed** 2019-10-17 02:29 UTC
Labels: Bug

**Comment by mikeminutillo** [comment] 2019-10-17 02:58
🎉 🎆 💯 🌮 🍻

**Comment by tmasternak** [comment] 2019-10-17 08:12
@mikeminutillo you did all the work, we just put the code in ;).
