### ISSUE TITLE
SagaUpdatedMessage handler can cause lots of concurrency exceptions

### ISSUE THREAD

**Issue by johnsimons** [Particular/ServiceControl#403] opened 2014-10-29 00:32 UTC
## Who's affected
Anyone using the [Saga plugin](http://docs.particular.net/servicecontrol/plugins/saga-audit) for ServiceControl

## Symptoms
When a `SagaUpdatedMessage` message is [handled](https://github.com/Particular/ServiceControl/blob/7db35f37e92c2e949ac111003dc05826387934be/src/ServiceControl/SagaAudit/SagaUpdatedHandler.cs), we attempt to create a new or update an existing raven document.

In an environment that sends lots of (100+) `SagaUpdatedMessage` messages to ServiceControl and the `SagaId` is the same, when we attempt to save the updated saga we are very prone to get a concurrency exception because ServiceControl processes messages using [multiple threads](https://github.com/Particular/ServiceControl/blob/7db35f37e92c2e949ac111003dc05826387934be/src/ServiceControl/ConfigTransportConfig.cs#L13).

Because in ServiceControl we only have FLR enabled ([SLR is disabled](https://github.com/Particular/ServiceControl/blob/7db35f37e92c2e949ac111003dc05826387934be/src/ServiceControl/Bootstrapper.cs#L36)), the chances of these messages ending up in the ServiceControl error queue is quite high.

We have had a report of this exact situation occurring.

--

### Proposal
Change the way we store saga history so that instead of using a single document, we split it into multiple documents.
So we would end-up with a `SagaHistory` document and multiple standalone `SagaStateChange`.
This way the `SagaUpdatedMessage` handler would only do inserts into raven.
We would then create an index that merges all saga info into a single output.

**Comment by Romiko** [comment] 2015-01-12 04:35
Hi,

I can confirm this issue is ServiceControl. If I delete all the .dll files for my endpoint to use SC e.g. ServiceControl.Plugin.SagaAudit.dll,ServiceControl.Plugin.DebugSession.dll etc, and disable auditing, this issue goes away.

**Comment by sfarmar** [comment] 2015-01-16 07:11
https://nservicebus.desk.com/agent/case/8600

```
We urgently require this to be fixed. It is extremely easy to reproduce.
Just create a saga that handles one type of message and send the same
message to it multiple times. On my machine sending 20 messages or more
will create the PUT request issues in Raven.

I am holding off our production to deployment until we have this issue with
ravenbdb concurrency fixed for SAGA correlation.
```

**Comment by andreasohlund** [comment] 2015-01-16 15:53
The workaround for the user is to remove the saga audit plugin since its only meant for diagnostics purposes and wasn't meant for high throughput scenarios. (not saying we shouldn't fix this timely)

cc @sfarmar

**Comment by gbiellem** [comment] 2015-04-15 05:49
@simoncropp:  this is now complete?
@SzymonPobiega I know you were looking at this as well re perf testing.  Any update?

**Comment by SzymonPobiega** [comment] 2015-04-15 06:37
@gbiellem got stack with my tests on some bizzare bahavior in json.net. We moved some types from one assembly to another and there seems to be no good way in telling Raven/Json.net how to handle that.

**Comment by SimonCropp** [comment] 2015-04-15 07:58
@gbiellem from my perspective this is done.

**Comment by SimonCropp** [comment] 2015-04-16 03:01
@SzymonPobiega would this work for your case https://msdn.microsoft.com/en-us/library/ms404275%28v=vs.110%29.aspx  ?

**Comment by SzymonPobiega** [comment] 2015-04-16 03:24
@SimonCropp could work. I'll try. I finally managed to debug the issue. It was related to one of Raven's converters that bypassed the type binding feature of json.net.

@gbiellem Regarding performance I noticed saga migration throughput between 10 and 20 documents/s.

**Comment by johnsimons** [comment] 2015-05-29 00:33
Another user bitten by this https://nservicebus.desk.com/agent/case/11057

**Comment by DavidBoike** [comment] 2015-10-06 18:20
Is this really in progress?

**Comment by ramonsmits** [comment] 2015-10-08 06:25
@simoncropp Any progress on this?

**Comment by SimonCropp** [comment] 2015-10-08 06:27
plan was to wait for the next release of SC, which will do the cleanup of old saga data, before proceeding with the split. So as to mitigate the load caused by these changes

**Comment by andreasohlund** [comment] 2015-10-08 07:15
Should we reword this one and consider this done + raise a new issue to track the things left to do?

**Comment by indualagarsamy** [comment] 2015-10-13 18:30
@simoncropp  - ping. Can we close this issue like @andreas suggested ?

**Comment by johnsimons** [comment] 2015-10-26 01:53
Fixed as part of #561

**Comment by johnsimons** [comment] 2016-02-17 01:17
We are not planning to fix this

**Comment by johnsimons** [comment] 2016-04-12 22:38
This is still an issue, and it is not fixed.

**Comment by johnsimons** [comment] 2016-04-13 21:41
Dear platform-dev-squad,

https://github.com/Particular/ServiceControl/issues/403 is still quite problematic for our users.
The saga audit plugin puts quite a lot of resource pressure on a ServiceControl instance because of the way we are doing the inserts and the amount of data being generated.
Even-though we recommend the usage of this plugin to be only for DEV, it still breaks in that environment, which means the promise of debugging sagas while in DEV is somehow broken (see https://nservicebus.desk.com/agent/case/17905).
Given that this is a feature that we have invested so much (and is fully supported), I believe this should be considered to be next in line.
We already have all the work that @SimonCropp put on to address this issue in https://github.com/Particular/ServiceControl/pull/561, I believe the work necessary to rebase that old PR and put it out there is not a lot.
Can you consider this one to be "next in line".

**Comment by andreasohlund** [comment] 2016-04-19 05:56
Not sure why my user added it to in progress (was sleeping 1 h ago :), removing the label

**Closed** 2016-05-04 23:48 UTC
Labels: Type: Bug
