### ISSUE TITLE
If `!disable` is used as the audit ingestion queue at install, install fails

### ISSUE THREAD

**Issue by ramonsmits** [Particular/ServiceControl#2268] opened 2020-11-10 18:03 UTC
![image](https://user-images.githubusercontent.com/152998/98706375-0fede600-237f-11eb-95b6-d716b1071f9a.png)

```
ISSUES ADDING INSTANCE:
Could not add new instance because of the following errors:
ServiceControl.Audit.exe threw an error when creating queues. This typically indicates a configuration error. The error output from ServiceControl.Audit.exe was:

Unhandled Exception: System.ArgumentException: Endpoint name must not be empty
Parameter name: endpointName
   at NServiceBus.Raw.RawEndpointConfiguration.ValidateEndpointName(String endpointName)
   at NServiceBus.Raw.RawEndpointConfiguration..ctor(String endpointName, Func`3 onMessage, String poisonMessageQueue)
   at NServiceBus.Raw.RawEndpointConfiguration.Create(String endpointName, Func`3 onMessage, String poisonMessageQueue)
   at ServiceControl.Audit.Infrastructure.RawEndpointFactory.CreateAuditIngestor(String name, ...
Please verify the details or contact support.
```

**Comment by danielmarbach** [comment] 2020-11-18 10:58
Duplicate of https://github.com/Particular/ServiceControl/issues/2197. Closing

**Closed by danielmarbach** 2020-11-18 10:58 UTC
