### ISSUE TITLE
Event failing on multiple logical subscribers can results in data loss

### ISSUE THREAD

**Issue by ramonsmits** [Particular/ServiceControl#842] opened 2016-11-11 16:40 UTC
### Symptoms
When an event is published to multiple logical subscribers and the message processing fails for more than one SC treats all failed messages as a single failed message and stores them in single document.  

As a result:
   * At any given moment in time the user sees only single failed message instead of all that actually failed
   * The users is able to request retry only for the message that failed most recently
   * Failed messages with status other than `Unresolved` get deleted after `Error Retention Policy` so any hidden, failed messages will get deleted without users knowing about it

### Who's Affected
Any version of ServiceControl prior to v1.27.0. with endpoints on version 5 and less.

**Comment by mikeminutillo** [comment] 2016-11-11 16:58
That shouldn't be. Each of the failed messages in the database have a
unique ID made up of the message is and the processing endpoint (which for
a failed message should be the contents of the FailedQ header).

**Comment by ramonsmits** [comment] 2016-11-11 18:30
We ( @bording @kbaley and me) tried to reproduce it by modifying the pubsub sample. https://github.com/ramonsmits/docs.particular.net/tree/servicecontrol-issue-842/samples/pubsub/Core_6

The same handler is present in both subscribers and that does result in a grouping issue in ServiceControl. The same group contains messages for different logical endpoints because the grouping is done on the handler name + exception.

When we retried the group the messages got send to the correct logical endpoint queues.

Based on this I changed the label from critical bug to bug as I think that isn't how the grouping should work.

**Comment by johnsimons** [comment] 2016-11-11 21:21
> Based on this I changed the label from critical bug to bug as I think that isn't how the grouping should work.

@ramonsmits can you please raise a different issue explaining how you think groups should work ? 

Also, given the issue raised is not an issue, it works as designed, should we close this ?

**Comment by johnsimons** [comment] 2016-11-11 21:28
@ramonsmits btw, we have added the capability of supporting different strategies for grouping and recently we have added [by message type](https://github.com/Particular/ServiceControl/pull/781), I believe ServicePulse will include this option [soon](https://github.com/Particular/ServicePulse/issues/330), maybe you want to chime in there ?

**Comment by mikeminutillo** [comment] 2016-11-14 02:19
Grouping is not the problem described by the Google Groups post. 

When ServiceControl ingests a failed message it stores it in a FailedMessage document. This document contains a collection of ProcessingRequest and a collection of FailureGroups. 

If the problem is related to the grouping mechanism then you would expect to find two different FailedMessage documents with the same Group. This is the expected behavior and it isn't a bug. If this group gets retried, both endpoints will receive their own copy. 

What the GG post describes is both messages appearing as ProcessingAttempt records in a single FailedMessage document. This will cause SC to treat the message as a single message. When it gets retried, only the most recent Processing Attempt will be retried so one endpoint will miss out. 

The code to determine the Id of the FailedMessage document is calculated using the message Id and the Processing Endpoint name. The code to determine Processing Endpoint Name is [here](https://github.com/Particular/ServiceControl/blob/master/src/ServiceControl/Infrastructure/TransportMessageExtensions.cs#L68). 

```CSharp
public static string ProcessingEndpointName(this TransportMessage message)
{
	string endpoint;

	if (message.Headers.TryGetValue(Headers.ProcessingEndpoint, out endpoint))
	{
		return endpoint;
	}

	if (message.ReplyToAddress != null)
	{
		return message.ReplyToAddress.Queue;
	}

	// If the ReplyToAddress is null, then the message came from a send-only endpoint.
	// This message could be a failed message.
	if (message.Headers.TryGetValue("NServiceBus.FailedQ", out endpoint))
	{
		return endpoint;
	}
	string messageTypes;
	if (message.Headers.TryGetValue(Headers.EnclosedMessageTypes, out messageTypes))
	{
		throw new Exception($"No processing endpoint could be determined for message ({message.Id}) with EnclosedMessageTypes ({messageTypes})");
	}

	throw new Exception($"No processing endpoint could be determined for message ({message.Id})");
}
```

For a Failed Message, the ProcessingEndpoint header won't be present but the ReplyToAddress might be. That means we never get to the FailedQ header which is what we are expecting to see for a Failed Message. 

This code looks incorrect but I am unsure what the consequences are of updating it. I believe we'd have to recalculate and potentially update the document Id of every Failed Message in the database. Not only that, we'd need to recalculate all of the document Ids for all of the Processing Attempts and potentially re-arrange them across FailedMessage documents.

This code has looked like this for quite some time.

**Comment by ramonsmits** [comment] 2016-11-14 08:16
@johnsimons You are right, that is another issue. I've commented on https://github.com/Particular/ServicePulse/issues/330

**Comment by SzymonPobiega** [comment] 2016-11-14 10:57
@mikeminutillo @ramonsmits  Does it also mean that marking a failure as resolved also does not work? because when an audited message arrives we use "processing endpoint" (destination) to build the address but the original failed message document used "reply to" (source).

If so then just fixing the algorithm and using the FailedQ from now on should solve the problem for new messages and at least not make it worse for the existing ones.

**Closed** 2016-11-17 10:40 UTC
Labels: Critical Bug
