### ISSUE TITLE
Decouple Service Control from RavenDB embedded

### ISSUE THREAD

**Issue by petersgiles** [Particular/ServiceControl#563] opened 2015-10-08 23:57 UTC
Task force: @mauroservienti @colin-higgins

Related to 

https://github.com/Particular/PlatformDevelopment/issues/211
https://github.com/Particular/PlatformDevelopment/issues/298
https://github.com/Particular/PlatformDevelopment/issues/344
https://github.com/Particular/PlatformDevelopment/issues/349
https://github.com/Particular/PlatformDevelopment/issues/350
https://github.com/Particular/PlatformDevelopment/issues/422

### Description

There has been some discussion recently around decoupling Raven DB Embedded from ServiceControl. It would benefit customers with high volume audit requirements to be able to have more control over the storage choice. 

Since there are 6 or more issues related to this one, it seems pretty clear that something needs to be done about it.

### Customer Communication

We have improved Particular's Audit capability by giving you more choice in how you store your audit information.

### Impact Assessment

Improves Performance in high volume scenarios
Improves Customer Ability to Tweak Performance

### Alignment with Vision

Improves Performance and Support  

#### Pre-conditions
- [x] Some initial performance metrics on Raven 2.0 - 3.0 (https://github.com/Particular/PlatformDevelopment/issues/422)
- [x] Spike SQL Server audit persistence (https://github.com/Particular/PlatformDevelopment/issues/349) Issue is closed but plan of action not complete!?!?!

#### Implement
- [ ] Decouple SC from Raven Embedded
- [ ] Implement new SQL Persistence
- [ ] Implement new Raven Persistence
- [ ] Implement other new Persistence (Mongo, PostgreSQL)

#### Document
- [ ] Document new configuration options
- [ ] Document performance metrics for difference persistences

#### Done
- [ ] Ready Customer Communications
- [ ] Pre Release user groups demo

**Comment by petersgiles** [comment] 2015-10-09 01:25
@mauroservienti @mikeminutillo you guys interested?

**Comment by sfarmar** [comment] 2015-10-09 11:40
@petersgiles I'de be happy to contribute if i can

**Comment by colin-higgins** [comment] 2015-10-09 14:08
I'd love to help too. I have a fair bit of document db experience (Raven and Mongo) and a fair bit of MS SQL experience too.

**Comment by mauroservienti** [comment] 2015-10-09 16:48
Sure, here I am :-)

**Comment by petersgiles** [comment] 2015-10-19 02:10
@mauroservienti @colin-higgins what do we need to get this one ready?

**Comment by weralabaj** [comment] 2015-10-19 06:09
@petersgiles Here are some recent discussions regarding SC scalability options which you might find useful:
Meeting recording: https://drive.google.com/a/nservicebus.com/file/d/0B2yu93f3hGFKVjZhalQ3aEFHQUE/view?usp=sharing
Slide Deck: https://drive.google.com/a/nservicebus.com/file/d/0B2yu93f3hGFKcTFVb0kxUl9PUU0/view?usp=sharing
The important questions I think need to be answered even before you start working on getting this ready:
1. Given Mauro's experiments with external Raven does it even make sense to consider that option? Will it solve problems? Does it also require significant changes in architecture to address issues we have?
2. Do we want to change the current version of SC or leave that one aside for customers with small needs and start working on a new version from scratch?
3. One challenge with SQL is full-text search. I guess to large extent the need for that might be mitigated by better filtering, but Danny should be involved in that decision.

**Comment by tclark15** [comment] 2015-10-21 16:44
We are a Particular customer and use ServiceControl in our environments.  We have unique use case in that we audit all of our NServicebus applications, and have run into performance issues with embedded RavenDB and ServiceControl. It doesnt seem to want to scale to meet our message volume.  I saw the thread for the decoupling of RavenDB, and  want to know you guys thoughts on how to improve performance.  Also, we use MongoDB extensively and would want MongoDB as an option if you guys do decouple Ravendb from persistence for ServiceControl.

I attempted to access the links above to look at the slide and listen to the meeting recording but I'm unable to access them.  (gmail account: tclark15@gmail.com)

**Comment by mauroservienti** [comment] 2015-10-21 17:36
Would you be able to share more details regarding the business scenario and the throughput requirements?


Sent by Outlook for Android



From: tclark15

Sent: Wednesday, October 21, 18:44

Subject: Re: [ServiceControl] Decouple Service Control from RavenDB embedded (#563)

To: Particular/ServiceControl

Cc: Mauro Servienti



We are a Particular customer and use ServiceControl in our environments. We have unique use case in that we audit all of our NServicebus applications, and have run into performance issues with embedded RavenDB and ServiceControl. It doesnt seem to want to scale to meet our message volume. I saw the thread for the decoupling of RavenDB, and want to know you guys thoughts on how to improve performance. Also, we use MongoDB extensively and would want MongoDB as an option if you guys do decouple Ravendb from persistence for ServiceControl.


I attempted to access the links above to look at the slide and listen to the meeting recording but I'm unable to access them. (gmail account: tclark15@gmail.com)

**Comment by dannycohen** [comment] 2015-10-22 06:35
@petersgiles - See meeting recording in https://particularsoftware.slack.com/archives/platform-development/p1445421197000105

Lots of activities going on. Interesting question is how does the decoupling (by itself) move us forward (i.e. what are the dependencies of this issue in achieving some of the tentative goals discussed in the meeting).

Thoughts ?

**Comment by tclark15** [comment] 2015-10-22 16:31
Our business requirement with ServiceControl is to maintain a 3 day retention of messages so we have the ability to look back over the weekend to troubleshoot if any issues occurred. Our current message volume is between 14 – 15 Million messages per day. This has resulted with our RavenDB Datafile to grow to around 350GBs.

ServiceControl runs on a 24 Core Server with 50GBs of RAM. RavenDB sits on a RAID 6 Physical Platter (non SSD) that is exclusively for Raven. The issue we’ve come into and would like to address is caused by the retention policy runs. When the deletes run to remove the stale messages, it bogs down Raven. This in turn limits the ability of ServiceControl to keep up with our Audit queue causing a cycle of our queue backing up. For NOSQL databases the primary one we use is MongoDB. We would like to have ServiceControl decoupled from RavenDB with the ability to hook into MongoDB which we are much more familiar with. This also allows us to setup our own retention within MongoDB to better handle our requirements and throughput.


Troy Clark | Applications Operations Manager
e  |  troy.clark@greatcall.com<mailto:troy.clark@greatcall.com>
p  |  858.720.7529  c  |  619.372.2703
10935 Vista Sorrento Pkwy, Suite 200  |  San Diego, CA 92130
[cid:image001.jpg@01CE1C18.D63DF2E0]

**Comment by CraigKennedy** [comment] 2015-11-16 12:35
+1 for a mongo option.  We use mongo elsewhere in our infrastructure.  Our only case for Raven is tied to ServiceControl.  The problem comes in when we need to support it.  We have many people with mongo skills, but very few with Raven experience beyond knowing that it is a document database.

**Comment by petersgiles** [comment] 2015-11-19 23:57
I'm removing myself from the task force for now since I'm currently in no position to commit any time to it.
If and when a task force lead is assigned and the issue is being driven forward, please feel free to ping me if you feel I can be of value and/or you'd like me to be a task force member.

**Comment by johnsimons** [comment] 2016-02-17 01:31
IMO, this is way too big to proceed, @Particular/servicecontrol-maintainers should we close this ?

We all agree that we need to slowly split our capabilities, but not sure if this is the way to go.

**Comment by mauroservienti** [comment] 2016-02-17 08:50
Well, I think that decoupling ServiceControl from the storage with the goal of allowing the user to plugin different storage types is an utopia we should not try to follow.

I don't think that this needs to be closed because too large, the issue remains: do we want to remove the dependency from the RavenDB embedded version? Or from RavenDB at all?

**Comment by sfarmar** [comment] 2016-02-17 09:12
:+1 this is a single issue that we can deal with as  one aspect of performance of SC.

Other aspects of performance and scale need to be addressed, but removing the embedded Raven is the first step, the second would be to enable other persistent stores (SQL, Mongo, Plug your own)

**Comment by gbiellem** [comment] 2016-02-18 03:18
I have disagree @sfarmar 

I agree with what @mauroservienti said ...

> Well, I think that decoupling ServiceControl from the storage with the goal of allowing the user to plugin different storage types is an utopia we should not try to follow.

I also think that this kind of thinking is still treating ServiceControl as a monolith  app. We already agreed that the goal is to breaking ServcieControl it into capabilities. Those capabilities may have different storage requirements and that should drive how we move forward on storage

**Comment by johnsimons** [comment] 2016-02-18 03:21
> Those capabilities may have different storage requirements and that should drive how we move forward on storage

:+1: 

And with that I think we should close it, and re-evaluate based on capability

**Comment by mauroservienti** [comment] 2016-02-18 06:03
> Those capabilities may have different storage requirements and that should drive how we move forward on storage

:+1: 

> And with that I think we should close it, and re-evaluate based on capability

Agree, shall we start an `epic` related to the componentization so that we can start linking issues and not lose track of them?

**Closed** 2016-02-18 06:22 UTC
Labels: Size: M, Type: Refactoring

**Comment by johnsimons** [comment] 2016-02-18 06:25
> shall we start an epic related to the componentization so that we can start linking issues and not lose track of them?

Not sure @mauroservienti, what is the benefit you see in doing that?

**Comment by mauroservienti** [comment] 2016-02-18 06:33
We need to keep track of the big picture, if an `epic` is not relevant or add no value, yet, a `label` can be a good solution.
