### ISSUE TITLE
Customer cannot start as non-admin when Raven exposed

### ISSUE THREAD

**Issue by DavidBoike** [Particular/ServiceControl#709] opened 2016-04-12 19:16 UTC
A customer reported to @colin-higgins:

> As we need to have access to the RavenDB of ServiceControl, I configured the Expose RavenDB option in the config-file. After that the service can only be started with an user of the administrator-group. Can we get around this issue because we don't want to have this situation?

Is it possible that the ServiceControl installer sets up a UrlAcl for the API endpoint, but does not do the same for the Raven endpoint?

Perhaps Colin will be able to add more information.

**Comment by johnsimons** [comment] 2016-04-12 22:55
My question is: 

> As we need to have access to the RavenDB of ServiceControl

Why ?

**Comment by gbiellem** [comment] 2016-04-13 02:20
@DavidBoike  @johnsimons 

Closing this as a duplicate of https://github.com/Particular/ServiceControl/issues/625
Workaround is already noted there

**Closed by gbiellem** 2016-04-13 02:20 UTC
Labels: Size: S, Type: Bug
