### ISSUE TITLE
Raven 2.5 -> 3.5 upgrade

### ISSUE THREAD

**Issue by SzymonPobiega** [Particular/ServiceControl#1144] opened 2018-05-08 07:58 UTC
80GB, 300GB, the largest we have ever seen is ~800GB

We want to perform a large-ish migration, document the results, and maybe issue a warning at upgrade time requesting that customers get in contact with us before starting a migration on a larger database.

### PoA:

- [x] Documentation - Add section to the doco that explains how long it might take by hinting at the 300 GB tests we ran
- [x] Documentation - Reemphasize again with a warning that it might take considerable amount of time to migrate the storage format plus the indexes to catch up
- [x] Documentation - Add documentation to explain the multi instance migration approach as an alternative for people who don't want to go through this long migration
- [x] Documentation - Explain error message migration in multi-instance mode
- [x] Installer - Focus on the installation experience to make the database file format modal window not disappear and add maybe text warn that this can take a lot of time
- [x] Installer - Make sure the installer after upgrade deletes the index definitions and indexes and ACKs the errors
- [x] Installer - Timebox to spike progress indicator
- [x] Installer - Recommend multi-instance mode over upgrade if DB is over a certain size
- [x] SC - add endpoint indicating upgrade process
- [x] Pulse - display indicator showing that indexes are still being upgraded
- [x] Test
- [x] Create notification email
- [ ] Identify customers and notify of release
- [x] Create announcement - @williambza
- [ ] Release

**Comment by SzymonPobiega** [comment] 2018-05-08 07:59
@danielmarbach can you updated this issue (I converted a card created by @mikeminutillo ) with the results of your tests and close it?

**Comment by WilliamBZA** [comment] 2018-05-21 10:43
Current status:

Upgrading small datatases (for some value of small) takes a reasonable amount of time. When upgrading larger databases (300Gb) then upgrade process takes a more random period of time. We should warn about the downtime before doing the upgrade.

A second problem is that we have encountered an indexing problem during the upgrade, documented [here](https://groups.google.com/forum/#!topic/ravendb/tTvSA2-44Wc). The solution of `delete the index` is problematic.

We are now checking if we can detect that failure and delete the problematic indexes programmatically thereby making the process more robust.

**Comment by danielmarbach** [comment] 2018-05-22 14:19
The storage format migration for 300 GB data took

Slower IO: 

Attempt 1: 4h 35 min
Attempt 2: 4h 10 min
Attempt 3: 3h 55 min

Faster IO:

Attempt 1: 2h 40 min
Attempt 2: 3 h 53 min

Indexings can roughly index 9-10 GB per hour
so it takes them roughly 31 h to catch up on the 300 GB database version. The tools operate even though the indexes are stale. RavenDB tries hard to index meaningful data first.

Following steps proposed to move forward

 - Add section to the doco that explains how long it might take by hinting at the 300 GB tests we ran
- Reemphasize again with a warning that it might take a considerable amount of time to migrate the storage format plus the indexes to catch up
- Explain the multi-instance migration approach as an alternative for people who don't want to go through this long migration
- Focus on the installation experience to make the database file format modal window not disappear and add maybe text warn that this can take a lot of time
- Make sure the installer after the upgrade deletes the index definitions and indexes and ACKs the errors
- Test again and release


Despite what we have seen with the initial tests with smaller databases we got confirmed that upgrading indexes is not really possible. `IndexCreation.Create ` will hang and throw after a long period of time if you try to do so which lets SC crash (the exception happens in the bootstrapper). As outlined above the suggested workaround is to delete the indexes. This is OK since we assumed that in the worst case we have to reindex everything anyway. 


![image](https://user-images.githubusercontent.com/174258/40368246-9e87802c-5ddb-11e8-98a8-23adf69c8605.png)


The indexes can be deleted by deleting the index folders. If we delete both the definition and the index folder the UI (only visible in maintenance mode) shows errors that have to be acked. Ideally the installer would have to do this. Otherwise, we have to explain those errors somewhere.

**Comment by danielmarbach** [comment] 2018-05-25 12:04
A simple upgrade progress is implemented by forwarding the esent upgrade log 1:1 to the UI

![upgradeprogress](https://user-images.githubusercontent.com/174258/40543372-5b9da70a-6024-11e8-829a-0ad454c0180b.gif)

**Comment by WilliamBZA** [comment] 2018-05-28 07:28
Spending some time spiking a re-index tracker. Other than that, documentation still needs to be finished and then we can release.

**Comment by WilliamBZA** [comment] 2018-05-29 07:49
SP PR has been submitted

**Comment by danielmarbach** [comment] 2018-06-05 10:49
Closing this issue since we are about to release

**Closed by danielmarbach** 2018-06-05 10:49 UTC
Labels: Improvement

**Comment by danielmarbach** [comment] 2018-06-05 12:08
ServiceControl has been released and announced in [the discussion group](Improved ServiceControl stability with version 2). An internal announcement was done to inform all engineers doing support. Next step is to reach out to customers and engage with them proactively.

**Comment by andreasohlund** [comment] 2018-06-07 06:48
H&M onpremise responded that they have been running fine with SC for sometime and will upgrade sometime after the summer so I've ticked that box in the POA

**Comment by danielmarbach** [comment] 2018-06-08 07:50
A quick wrap up of the approach we used. We used Azure IaaS with hosts that have enough IO capacity. Then we created multiple disks and attached those to the VM host. The disks were striped together to maximize the IOPs up to our needs by using the storage pool feature of Windows 2016

Script to attach disks

```
clear
 
# RM stands for resource manager, and is the new way of managing things in Azure
 
# you need to login the first time using this command
# Login-AzureRmAccount
 
$vm = Get-AzureRmVM -ResourceGroupName "ravenmigrations" -Name "ravenfast"
 
# adds 8 disks
for($i=1; $i -le 32; $i++) {
    $name = "ravenfast-disk{0:00}" -f $i
    $lun = $i - 1
 
    $diskConfig = New-AzureRmDiskConfig `
    -Location "westeurope" `
    -CreateOption Empty `
    -DiskSizeGB 512
    $dataDisk = New-AzureRmDisk `
    -ResourceGroupName "ravenmigrations" `
    -DiskName $name `
    -Disk $diskConfig
 
    $vm = Add-AzureRmVMDataDisk `
    -VM $vm `
    -Name $name `
    -CreateOption Attach `
    -ManagedDiskId $dataDisk.Id `
    -Lun $lun
}
 
$vm.DataDiskNames
 
# uncomment when you are ready, this updates the VM on azure!
Update-AzureRmVM -ResourceGroupName "ravenmigrations" -VM $vm
```

Script to query for stale indexes after storage format migration

```
$staleIndexes = 1
do
{
    $j = Invoke-WebRequest 'http://localhost:33333/storage/stats' | ConvertFrom-Json
    $staleIndexes = $j.StaleIndexes.Count
    $information = @(

        [pscustomobject]@{

        Time = $(Get-Date -format 's')

        StaleIndexes  = $staleIndexes

        Data  = $j.StaleIndexes | ConvertTo-Json

        }

    )
    $information | Export-Csv -Path  C:\stats.csv -Append -NoTypeInformation
    Write-Host $information
    sleep 60
}
while($true)
```
