### ISSUE TITLE
Instance config changes are not reflected in the management UI

### ISSUE THREAD

**Issue by adamralph** [Particular/ServiceControl#973] opened 2017-06-13 13:25 UTC
E.g. after changing the port of a current SC instance in the management utility, the old port is still shown both in the view of the instance and in the edit screen for the instance (although the port the instance is running on _is actually changed_).

**Comment by mikeminutillo** [comment] 2017-06-14 04:56
@adamralph is this a duplicate of https://github.com/Particular/ServiceControl/issues/964

**Closed** 2017-06-14 04:56 UTC

**Comment by adamralph** [comment] 2017-06-20 16:22
@mikeminutillo 👍 I did a search before raising this, but I missed it.
