### ISSUE TITLE
HttpRequestException when Version check fails

### ISSUE THREAD

**Issue by danielmarbach** [Particular/ServiceControl#2262] opened 2020-11-05 08:17 UTC
![image](https://user-images.githubusercontent.com/174258/98214658-10354e00-1f47-11eb-8300-2371d9ad4b4a.png)

The version check assumes the S3 API to be available

https://github.com/Particular/ServiceControl/blob/master/src/ServiceControl.Config/UI/Shell/VersionCheckerHelper.cs#L27-L43

in addition to that the code using HttpClient and HttpHandler in non-standard ways (i.ex. HttpClient should not be used in a using block)

This behavior got introduced in 4.13

https://github.com/Particular/ServiceControl/pull/2159

**Comment by danielmarbach** [comment] 2020-11-05 08:19
// cc @mikeminutillo @seanfarmar @tmasternak pinging you since you have been involved in the above changes

**Comment by WilliamBZA** [comment] 2020-11-12 08:02
Duplicate of https://github.com/Particular/ServiceControl/issues/2240

**Closed by WilliamBZA** 2020-11-12 08:02 UTC
Labels: Bug
