### ISSUE TITLE
Timeouts and timeoutsdispatcher are registered as endpoints, but they don't generate heartbeats so always stay "in red"

### ISSUE THREAD

**Issue by johnsimons** [Particular/ServiceControl#726] opened 2016-05-13 06:03 UTC
This was originally raised in https://github.com/Particular/ServicePulse/issues/340

This happens because when a timeout fails is sent to the error queue and then ServiceControl picks it up and registers that as an endpoint.
And obviously we then do not have heartbeats for satellites and hence these are seen in error all the time.

**Comment by johnsimons** [comment] 2016-05-13 06:03
@pablocastilla issue moved here

**Comment by johnsimons** [comment] 2016-05-13 06:04
@Particular/servicecontrol-maintainers not sure how we are going to fix this one!

**Comment by mikeminutillo** [comment] 2016-05-13 08:21
So the issue is that we are treating timeouts as a separate endpoint? 

From SCs perspective the rules are easy. If we see an endpoint we've never seen before we enlist it for monitoring. Once enlisted it's either alive or dead. Maybe we need a more nuanced state machine so we can hear about an endpoint and display it on screen without declaring it dead. 

The simple workaround is to disable monitoring of that endpoint in Pulse. That could be painful if you have a lot of endpoints with Timeout Manager installed though.

**Comment by pablocastilla** [comment] 2016-05-13 14:35
How about a special filter in service pulse? I just don't want to see it in
the web

**Comment by johnsimons** [comment] 2016-05-15 23:50
@mikeminutillo my issue with our current solution is that ServicePulse should not be making an endpoint "red" if a user does not have heartbeats installed, heartbeats is an optional plugin, IMO the endpoint should only be red if an endpoint has heartbeats on and we stop receiving the heartbeat. For endpoints that do not have heartbeats installed, I would disable that capability.

cc @pablocastilla

**Comment by pablocastilla** [comment] 2016-05-16 05:37
I agree, but in my case those endpoints have the heartbeat dll installed

**Comment by indualagarsamy** [comment] 2016-05-16 15:45
@johnsimons @mikeminutillo - Are timeout messages, control messages? If they are control messages, can we not filter from SC? i.e. if we can make a determination that the error messages are arriving from satellite queues, why should it get added to the Known endpoints list?

**Comment by johnsimons** [comment] 2016-08-18 01:08
> Are timeout messages, control messages? If they are control messages, can we not filter from SC?

Not all messages are control messages, but control or not, something is failing and we need to report on it.

> if we can make a determination that the error messages are arriving from satellite queues

I don't think we can determine if a message is from a satellite queue or not.

**Comment by johnsimons** [comment] 2016-08-18 01:09
@Particular/servicecontrol-maintainers I still think the way to address this issue is https://github.com/Particular/ServiceControl/issues/726#issuecomment-219322384, thoughts ?

**Comment by SzymonPobiega** [comment] 2016-10-26 12:21
@johnsimons Would that imply a third category/tab on `http://localhost:9090/#/endpoints` page:
 * Inactive endpoints
 * Active endpoints
 * Not monitored endpoints

**Comment by johnsimons** [comment] 2016-10-26 21:58
@SzymonPobiega that sounds right.
We need to involve @Particular/servicepulse-maintainers to make sure they are ok with this change.

**Comment by WojcikMike** [comment] 2016-10-27 10:25
@johnsimons can you elaborate a bit on your implementation? From what I understand at the moment when the endpoint is discovered and don't send heartbeats we assume that it failed. THe reason for that is  that every new endpoint is marked as monitored. What you are describing John would require us to by default add endpoints as unmonitored. Is this what you suggest?

**Comment by SzymonPobiega** [comment] 2016-10-27 10:34
@WojcikMike I believe that's the proposal. Add endpoints as "unmonitored". Move to "active" when HB is discovered. Move to "inactive" when there is no HB any more and the endpoint has previously been in "monitored" state

**Comment by WojcikMike** [comment] 2016-10-27 12:45
AFAIK there is no way to recognize that endpoint don't have HB. We mark endpoint as 'failed' when the HB don't show, which means that endpoint is not working. If you don't want to see that endpoint as failed you mark it as unmonitored. 

If we unmonitor every endpoint that don't send HB then HB feature is useless. Unless I misunderstood something or some feature works in a different way that I think it works

**Comment by SzymonPobiega** [comment] 2016-10-27 12:55
Hmmm well, I would say that if an endpoint never ever sent us a HB then it is unmonitored. We only mark an endpoint as down/inactive if we know it previously has sent a HB and is not sending them any more.

**Comment by pablocastilla** [comment] 2016-10-27 15:44
+1 to this :)

**Comment by johnsimons** [comment] 2016-10-27 23:30
@SzymonPobiega @WojcikMike 

> Add endpoints as "unmonitored". Move to "active" when HB is discovered. Move to "inactive" when there is no HB any more and the endpoint has previously been in "active" state

That is pretty much it 👍 
This works because the heartbeat includes the [endpoint name](https://github.com/Particular/ServiceControl.Plugin.Nsb5.Heartbeat/blob/9aaf6f2775382e7dde121c81105eb0db6e21dcf2/src/ServiceControl.Plugin.Nsb5.Heartbeat/Heartbeats.cs#L109) which equals the queue name so for satellite queues eg myendpoint.timeouts it would not match and therefore it would be unmonitored.
Now this is all theoretical, we need to validate this for all transport permutations and see if it works.

Also there is a catch, if a user decides to uninstall heartbeats from a previously beating endpoint there would be no way to move that endpoint from  "inactive" to "unmonitored", but to be honest I am not sure if we need to support it, thoughts ?

**Comment by pablocastilla** [comment] 2016-10-28 05:12
Maybe in that case the user could disable it manually in the configuration
tab

**Comment by johnsimons** [comment] 2016-10-31 05:29
@SzymonPobiega any other questions ? is it ok if i put your face against it ?

**Comment by SzymonPobiega** [comment] 2016-10-31 05:40
@johnsimons I think enough for start. I self-assigned it.

**Comment by SzymonPobiega** [comment] 2016-11-03 08:48
Well, it turns out it works as expected. I did a repro where I created my own satellite "FaultySatellite" that throws exceptions. I also had a handler that throws exceptions as a base line. I run the app twice and generated four failed messages: two in the satellite and two in the handler.

I opened SP and I can see only one endpoint "active". The satellite does not show as "inactive" endpoint. On the failed message list the message that failed in the satellite shows proper endpoint name "SatelliteFailureGenerator" (as in "ProcessingEndpoint" header). The "FailedQ" header points correctly to the satellite queue.

Am I missing something @johnsimons & @pablocastilla ? I used V6 endpoint to generate the failed messages.

**Comment by johnsimons** [comment] 2016-11-03 10:20
@SzymonPobiega 
I think we should try v5, it could be that "ProcessingEndpoint" header is not in v5 satellites ?
Also do you have heartbeats on ?

**Comment by SzymonPobiega** [comment] 2016-11-03 13:16
@johnsimons yes, I had HB on and working because I verified the endpoint is in the "active" tab. I'll try V5.

**Comment by SzymonPobiega** [comment] 2016-11-04 09:51
Check this and V5 does not add `NServiceBus.ProcessingEndpoint` header to failed messages (both coming from satellite and regular handler), only to audit messages. This is the reason the satellite is shown as a different endpoint.

How about we add this header in a patch release of NSB 5 instead of changing the way SC/SP works?

**Comment by johnsimons** [comment] 2016-11-06 23:16
> How about we add this header in a patch release of NSB 5 instead of changing the way SC/SP works?

Even though that header quite possible makes sense to be in satellites, I don't think we can just patch the core to fix the issue.
As it currently stands users are already affected by this and there is no easy way for them to fix it, even if we were to patch the core and the users update to it, it would still be broken and showing as a filed endpoint in ServicePulse.
As I said before, **the endpoint should only be red if an endpoint has heartbeats on and we stop receiving the heartbeat**, that is IMO still the correct way to fix this issue.

**Comment by WojcikMike** [comment] 2016-11-07 10:12
> As I said before, the endpoint should only be red if an endpoint has heartbeats on and we stop receiving the heartbeat, that is IMO still the correct way to fix this issue.

This approach has a drawback when you first try to start endpoint and you have the intention to use heartbeats but they are never recieved by SC. By explicit marking endpoint as monitored vs unmonitored we allow system to mark endpoint as red from the start. However to even mark endpoint as monitored vs unmonitored it needs to be discovered (failed message, audit or heartbeat). 

We could change that by default discovered endpoints are not monitored but user can change it.

**Comment by SzymonPobiega** [comment] 2016-11-07 13:33
@WojcikMike I am with @johnsimons on this. When I really really want to make sure newly deployed endpoints are monitored, I would double check it in SC and not rely on the red label showing me lack of heartbeat.

**Comment by WojcikMike** [comment] 2016-11-07 13:51
@SzymonPobiega I hear you, however I am always reluctant with magic processes and later on understanding why my endpoint is not showing as red in SP. However I can live with this automation.

**Comment by SzymonPobiega** [comment] 2016-11-07 14:03
@johnsimons speaking about a quick fix, users who are affected can go to configuration and disable monitoring of the offending satellite even now.

**Comment by johnsimons** [comment] 2016-11-08 00:34
> users who are affected can go to configuration and disable monitoring of the offending satellite even now.

@SzymonPobiega Agree, but really not optimal, I will mark this as an improvement.

So is there anything else that prevent us from proceeding ?

**Comment by SzymonPobiega** [comment] 2016-11-08 07:28
@johnsimons let me validate my plan of attack here before I jump into the code:

### Assumptions
1. Currently `KnownEndpoint` sets its `Monitored` property to `true` in the default constructor which means endpoints are monitored by default
2. Users can opt-out from monitoring via the *Configuration* tab
3. Endpoints with `Monitored` set to false do not show up in the *Endpoints Overview*

### PoA
1. Change the behavior of `KnownEndpoint` to set `Monitored` to `false` by default causing new endpoints that don't have HB plugin installed to not show up in *Endpoints Overview*
2. Validate that toggling the switch in *Configuration* makes the endpoint show up in *Endpoints Overview* as "inactive"
3. Validate that if a HB message is received for an endpoint that is not set to be monitored, it automatically switches to "monitored" mode (as active) and when the HB is gone, it shows up as "inactive" and the red label is present.

@WojcikMike @johnsimons does it sound good?

**Comment by johnsimons** [comment] 2016-11-08 07:45
@SzymonPobiega sounds like a plan

**Comment by WojcikMike** [comment] 2016-11-08 09:02
@SzymonPobiega sounds good.

> Validate that if a HB message is received for an endpoint that is not set to be monitored, it automatically switches to "monitored" mode (as active) and when the HB is gone, it shows up as "inactive" and the red label is present.

This will cause that you will not be able to mark as inactive endpoint that sends heartbeats. However I am struggling in what circumstances that would be needed.

**Comment by SzymonPobiega** [comment] 2016-11-08 14:37
I made a good progress on that in #838 . Can you guys take a look?

**Comment by johnsimons** [comment] 2016-11-22 02:49
@SzymonPobiega how is this coming along ?

**Comment by SzymonPobiega** [comment] 2016-11-22 07:23
@johnsimons from coding perspective this is done. There was one question you asked the maintainer group but nobody answered yet...

**Comment by WojcikMike** [comment] 2016-11-28 12:16
As this piece of code change the behavior should we make a doco PR before we close this?

**Comment by SzymonPobiega** [comment] 2016-11-28 12:46
Here's a doco pull @WojcikMike https://github.com/Particular/docs.particular.net/pull/2279. Please review. And good catch! Thanks!

**Comment by SzymonPobiega** [comment] 2016-11-28 13:48
Doco updated.

**Closed by SzymonPobiega** 2016-11-28 13:48 UTC
Labels: Improvement
