### ISSUE TITLE
Unable to add instances due to UrlAcl conflicts

### ISSUE THREAD

**Issue by ramonsmits** [Particular/ServiceControl#2591] opened 2021-07-09 07:36 UTC
I tried installing instances and got the following message and the installer stopped.

![image](https://user-images.githubusercontent.com/152998/125041177-c1712280-e098-11eb-88e0-728337cb9f12.png)

I had to manually remote entries via `netsh http delete urlacl`.

I don't understand why the installer didn't just continue. If these are actual errors it would be nice if the installer could resolve these issues as options COPY, FIX, CLOSE/OK.

**Comment by jpalac** [comment] 2023-06-19 03:33
Fix will be available in next SC release.

**Comment by tmasternak** [comment] 2023-06-21 08:27
We wrongly assumed this is a duplicate of #3566.

**Closed** 2023-06-21 08:29 UTC
Labels: Bug
