### ISSUE TITLE
SCMU changes the case of text entered in the Name field when filling the ServiceName fields

### ISSUE THREAD

**Issue by gbiellem** [Particular/ServiceControl#1730] opened 2019-08-12 03:44 UTC
User report: https://github.com/Particular/ServiceControl/issues/1767

When adding a new ServicecControl instance through the SCMU the case is being manipulated.  I'd expect the case to be preserved

![image](https://user-images.githubusercontent.com/2351700/62844882-a7413500-bd07-11e9-8ad6-52b4857ded94.png)

### POA
- [ ] Close user reported issue https://github.com/Particular/ServiceControl/issues/1767

**Comment by WojcikMike** [comment] 2019-08-12 07:18
Hey, @gbiellem thanks for raising it. We added it to our backlog of bugs that we will be working through. We will comment on this issue when we will fix that problem

**Comment by kbaley** [comment] 2021-01-18 19:11
Relabeled as an improvement as it doesn't affect the correctness of ServiceControl

**Comment by awright18** [comment] 2023-03-31 15:09
Closing this as duplicate of 
- #1767

**Closed by awright18** 2023-03-31 15:09 UTC
Labels: Improvement, candidate-for-next-release
