### ISSUE TITLE
Stop message ingestion when passing low on storage treshold

### ISSUE THREAD

**Issue by ramonsmits** [Particular/ServiceControl#2701] opened 2021-11-17 11:43 UTC
Currently SC shows a warning but still continues message ingestion. If the storage actually has no space left this can result in index corruption. By halting ingestion until the storage issue has been resolved prevent the instance to get in a corrupted state which takes considerable amounts of time to recover from.

**Comment by tmasternak** [comment] 2023-01-05 07:34
@ramonsmits is this a duplicate of https://github.com/Particular/ServiceControl/issues/2909?

**Comment by ramonsmits** [comment] 2023-01-05 16:52
> @ramonsmits is this a duplicate of https://github.com/Particular/ServiceControl/issues/2909?

Yes, it is

**Closed** 2023-01-05 16:52 UTC
Labels: Feature
